import { SimulationNodeDatum } from "d3-force";

type Node = {
  category: string;
  id: number;
  image: string;
  name: string;
  type: string;
  value: number;
  focused: boolean;
};
export type NodeType = SimulationNodeDatum & Node;

export type LinkType = {
  index?: number; // generated by D3Simulation
  source: NodeType;
  target: NodeType;
  connections: ConnectionType[];
  twoWay: boolean;
};

export type ConnectionType = {
  product: ConnectionNode;
  resources: ConnectionNode[];
  type: string;
};
export type ConnectionNode = { node: NodeType; count: number };

export type DataType = {
  nodes: NodeType[];
  links: LinkType[];
};
